apiVersion: v1
kind: Service
metadata:
  name: mern-budget-frontend
  namespace: mern-budget
spec:
  selector:
    app: mern-budget-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000