apiVersion: v1
kind: Service
metadata:
  name: mern-budget-mongo
  namespace: mern-budget
spec:
  selector:
    app: mern-budget-mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017