apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-budget-backend
  namespace: mern-budget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-budget-backend
  template:
    metadata:
      labels:
        app: mern-budget-backend
    spec:
      containers:
      - name: backend
        image: mbewd/mern-budget-backend:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URL
          value: "mongodb://mern-budget-mongo:27017/mern-budget"
      imagePullSecrets:
        - name: docker-config  # Specify the name of your Kubernetes secret here
