apiVersion: v1
kind: Service
metadata:
  name: mern-budget-frontend
  namespace: mern-budget
spec:
  selector:
    app: mern-budget-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001  # Choose a port in the 30000-32767 range
      name: site