apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-budget-mongo
  namespace: mern-budget
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-budget-mongo
  template:
    metadata:
      labels:
        app: mern-budget-mongo
    spec:
      containers:
      - name: mern-budget-mongo
        image: mongo:4.4
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mern-budget
          mountPath: /data/db
      volumes:
      - name: mern-budget
        emptyDir: {}