name: Deploy to Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Other build steps...

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'

      - name: Decode and configure Kubeconfig
        run: echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Configure kubectl with service account
        run: |
          kubectl config set-context --current --namespace=mern-budget
          kubectl config set-credentials github-actions --token="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"
          kubectl config set-context --current --user=github-actions

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/mern-budget-backend backend=mbewd/mern-budget-backend:latest -n mern-budget
          kubectl set image deployment/mern-budget-frontend frontend=mbewd/mern-budget-frontend:latest -n mern-budget
